const state={workers:[],devices:[],suites:[],jobs:[],library:[]};
const activeDeployments=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options){const r=await fetch(path,options),text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch(_){d={detail:text||r.statusText}}if(!r.ok||d.success===false)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';setTimeout(()=>el.style.display='none',3000);if(message==='Worker 已安装并成功注册')notifyCompletion('测试主机部署完成',message);else if(message.includes(' 已部署到 '))notifyCompletion('测试套件部署完成',message)}
function notifyCompletion(title,message){window.parent.postMessage({type:'cluster-notification',title,message,level:'success'},location.origin)}
function badge(s){return `<span class="status ${esc(s)}">${esc(s)}</span>`}
function render(){
 state.workers.sort((a,b)=>(a.id==='worker-local'?-1:b.id==='worker-local'?1:String(a.registered_at||'').localeCompare(String(b.registered_at||''))));
 document.querySelector('#workers').innerHTML=state.workers.map(w=>`<div class="card"><div class="card-title"><span>${esc(w.name||w.id)}</span><span>${badge(w.status)}${w.id!=='worker-local'?` <button class="worker-delete" onclick="deleteWorker('${esc(w.id)}')">删除主机</button>`:''}</span></div><p>${esc(w.hostname)} · ${esc(w.id)} · ${esc(w.address||'')}</p><div class="meta"><span>CPU ${w.cpu_percent}%</span><span>内存 ${w.memory_percent}%</span><span>磁盘 ${w.disk_free_gb}G</span><span>设备 ${state.devices.filter(d=>d.worker_id===w.id&&d.state!=='offline').length}</span><span>套件 ${state.suites.filter(s=>s.worker_id===w.id&&s.available).length}</span><span>任务 ${w.running_jobs}/${w.max_jobs}</span></div><div class="capabilities"><span class="cap ${w.capabilities?.ssh_user?'ok':''}">终端 ${w.capabilities?.ssh_user?'✓':'未配置'}</span><span class="cap ${w.capabilities?.novnc_port?'ok':''}">noVNC ${w.capabilities?.novnc_port?'✓':'未配置'}</span><span class="cap ${w.capabilities?.tradefed?'ok':''}">Tradefed ${w.capabilities?.tradefed?'✓':'不可用'}</span></div></div>`).join('')||'<div class="empty">暂无 Worker，请点击“添加主机”查看接入命令</div>';
 document.querySelector('#devices').innerHTML=state.devices.map(d=>`<tr><td>${esc(d.worker_id)}</td><td>${esc(d.serial)}</td><td>${badge(d.state)}</td><td>${esc(d.properties?.model||d.properties?.product||'')}</td></tr>`).join('');
 document.querySelector('#suites').innerHTML=state.suites.filter(s=>s.available).map(s=>`<tr><td>${esc(s.worker_id)}</td><td>${esc(s.suite_type)}</td><td>${esc(s.suite_version)}</td><td title="${esc(s.tools_path)}">${esc(s.tools_path)}</td></tr>`).join('');
 document.querySelector('#jobs').innerHTML=state.jobs.map(j=>`<tr><td>${esc(j.id.slice(0,16))}</td><td>${esc(j.assigned_worker_id)}</td><td>${badge(j.status)}</td><td>${esc(j.leases.map(x=>x.serial).join(', '))}</td><td>${esc(j.created_at)}</td><td><button onclick="showJob('${esc(j.id)}')">查看</button>${['running','dispatching'].includes(j.status)?` <button onclick="cancelJob('${esc(j.id)}')">停止</button>`:` <button onclick="deleteJob('${esc(j.id)}')">删除</button>`}</td></tr>`).join('');
 if(!activeDeployments.size)renderLibrary();
}
function formatBytes(v){const n=Number(v)||0;if(n>=1073741824)return `${(n/1073741824).toFixed(2)} GB`;if(n>=1048576)return `${(n/1048576).toFixed(1)} MB`;return `${n} B`}
function archiveFolder(name){return String(name).replace(/\.(tar\.gz|tar\.bz2|zip|tgz|tar)$/i,'').replace(/[^A-Za-z0-9._+-]+/g,'_')}
function renderLibrary(){const body=document.querySelector('#library');if(!body)return;const workers=state.workers.filter(w=>w.status!=='offline'&&w.id!=='worker-local');body.innerHTML=state.library.map((a,i)=>`<tr><td title="${esc(a.name)}">${esc(a.name)}</td><td>${formatBytes(a.size)}</td><td>${new Date(a.modified*1000).toLocaleString()}</td><td><select id="library-worker-${i}">${workers.map(w=>`<option value="${esc(w.id)}">${esc(w.name||w.id)}</option>`).join('')}</select></td><td><input id="library-folder-${i}" value="${esc(archiveFolder(a.name))}"></td><td><button class="primary" onclick="deployArchive(${i})" ${workers.length?'':'disabled'}>下发并解压</button> <span class="progress-wrap"><span class="progress-track"><span class="progress-bar" id="library-bar-${i}"></span></span><span class="deploy-progress" id="library-progress-${i}"></span></span></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Controller 套件目录中没有压缩包</td></tr>'}
async function loadLibrary(){const d=await api('/api/cluster/suite-library');state.library=d.archives||[];renderLibrary()}
async function waitCommand(id,progress,onProgress){for(let i=0;i<7200;i++){const d=await api(`/api/cluster/commands/${encodeURIComponent(id)}`),c=d.command;if(c.status==='completed')return c.result||{};if(['failed','cancelled'].includes(c.status))throw new Error(c.error||`${c.command_type}失败`);if(onProgress&&c.result?.downloaded_bytes)onProgress(c.result);else if(i%10===0)progress.textContent=`处理中 ${Math.floor(i/10)}s`;await new Promise(r=>setTimeout(r,1000))}throw new Error('操作超时')}
async function deployArchive(index){
 const archive=state.library[index],worker=document.querySelector(`#library-worker-${index}`).value,folder=document.querySelector(`#library-folder-${index}`).value.trim(),progress=document.querySelector(`#library-progress-${index}`),bar=document.querySelector(`#library-bar-${index}`);if(!worker||!folder)return;activeDeployments.add(index);
 try{
  bar.className='progress-bar';bar.style.width='2%';progress.textContent=`准备下发 ${formatBytes(archive.size)}…`;
  const ext=archive.name.toLowerCase().endsWith('.tar.gz')?'.tar.gz':(archive.name.match(/\.[A-Za-z0-9]+$/)?.[0]||'.zip'),safe=`suite-${Math.abs([...archive.name].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0))}${ext}`;
  const url=`${location.origin}/api/cluster/suite-library-download/${safe}/${encodeURIComponent(archive.name)}`;
  const accepted=await api('/api/cluster/suites/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:worker,url,filename:archive.name,size_bytes:archive.size})});
  const downloaded=await waitCommand(accepted.command_id,progress,p=>{const total=p.total_bytes||archive.size,ratio=total?Math.min(p.downloaded_bytes/total,1):0;bar.style.width=`${Math.max(2,Math.round(ratio*80))}%`;progress.textContent=`正在下发 ${formatBytes(p.downloaded_bytes)} / ${formatBytes(total)} (${Math.round(ratio*100)}%)`});
  bar.style.width='82%';progress.textContent='下载完成，正在解压…';
  const extracted=await api('/api/cluster/suites/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:worker,archive_path:downloaded.archive_path,target_dir_name:folder})});
  await waitCommand(extracted.command_id,progress);bar.style.width='';bar.className='progress-bar done';progress.textContent='部署完成';toast(`${archive.name} 已部署到 ${worker}`)
 }catch(e){bar.style.width='';bar.className='progress-bar failed';progress.textContent=`失败：${e.message}`;toast(e.message)}finally{setTimeout(()=>{activeDeployments.delete(index);renderLibrary()},15000)}
}
function updateJobOptions(){const wid=document.querySelector('#job-worker').value;const suite=document.querySelector('#job-suite'),device=document.querySelector('#job-device');const availableSuites=state.suites.filter(s=>(wid==='auto'||s.worker_id===wid)&&s.available);suite.innerHTML=[...new Map(availableSuites.map(s=>[s.suite_key,s])).values()].map(s=>`<option value="${esc(s.suite_key)}">${esc(s.suite_type)} ${esc(s.suite_version)}</option>`).join('');device.innerHTML=wid==='auto'?'<option value="">自动选择设备</option>':state.devices.filter(d=>d.worker_id===wid&&d.state==='available').map(d=>`<option value="${esc(d.id)}">${esc(d.serial)}</option>`).join('')}
async function refresh(){const button=document.querySelector('#refresh');if(button){button.disabled=true;button.textContent='刷新中…'}try{const [w,d,s,j,l]=await Promise.all([api('/api/cluster/workers'),api('/api/cluster/devices'),api('/api/cluster/suites'),api('/api/cluster/jobs'),api('/api/cluster/suite-library')]);Object.assign(state,{workers:w.workers,devices:d.devices,suites:s.suites,jobs:j.jobs,library:l.archives||[]});render()}catch(e){toast(e.message)}finally{if(button){button.disabled=false;button.textContent='↻ 刷新'}}}
async function createJob(){try{const device=document.querySelector('#job-device').value;const body={worker_id:document.querySelector('#job-worker').value,suite_key:document.querySelector('#job-suite').value,devices:device?[device]:[],device_count:1,owner_id:'web-cluster'};if(!body.worker_id||!body.suite_key)throw new Error('请选择 Worker 和套件');const d=await api('/api/cluster/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast(`任务已创建 ${d.job.id}`);await refresh();showJob(d.job.id)}catch(e){toast(e.message)}}
async function showJob(id){try{const [j,e,a]=await Promise.all([api(`/api/cluster/jobs/${id}`),api(`/api/cluster/jobs/${id}/events`),api(`/api/cluster/jobs/${id}/artifacts`)]);document.querySelector('#detail').hidden=false;document.querySelector('#job-detail').textContent=JSON.stringify(j.job,null,2);document.querySelector('#job-logs').textContent=e.events.map(x=>`[${x.source}] ${x.message}`).join('\n')||'暂无日志';document.querySelector('#artifacts').innerHTML=a.artifacts.map(x=>`<a href="/api/cluster/jobs/${id}/artifacts/${x.id}/download">${esc(x.filename)} (${x.size_bytes} bytes)</a>`).join(' · ');document.querySelector('#detail').scrollIntoView({behavior:'smooth'})}catch(e){toast(e.message)}}
async function cancelJob(id){try{await api(`/api/cluster/jobs/${id}/cancel`,{method:'POST'});toast('停止命令已下发');await refresh()}catch(e){toast(e.message)}}
async function deleteJob(id){if(!confirm('确定删除该任务历史及事件记录？'))return;try{await api(`/api/cluster/jobs/${id}`,{method:'DELETE'});toast('任务历史已删除');await refresh()}catch(e){toast(e.message)}}
async function deleteWorker(id){if(!confirm(`确定从集群删除 ${id}？该主机的设备和套件记录也会移除。`))return;try{await api(`/api/cluster/workers/${encodeURIComponent(id)}`,{method:'DELETE'});toast(`${id} 已从集群删除`);await refresh()}catch(e){toast(e.message)}}
function normalizedWorkerId(value){return String(value||'').trim().toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')}
function updateDeployCommand(){const id=normalizedWorkerId(document.querySelector('#new-worker-id').value)||'WORKER_ID',host=document.querySelector('#new-worker-host').value.trim()||'USER@HOST',address=host.includes('@')?host.split('@').slice(1).join('@'):'HOST',controller=document.querySelector('#controller-url').value.trim()||location.origin,root=document.querySelector('#suite-root').value.trim()||'~/GMS-Suite';document.querySelector('#deploy-command').textContent=`rsync -azR worker_agent scripts/install_cluster_worker.sh ${host}:~/gms-worker-setup/ && ssh ${host} 'cd ~/gms-worker-setup && bash scripts/install_cluster_worker.sh ${id} ${controller} WORKER_TOKEN - ${root} ${address}'`}
async function autoDeployWorker(){const button=document.querySelector('#auto-deploy');const body={worker_id:normalizedWorkerId(document.querySelector('#new-worker-id').value),ssh_host:document.querySelector('#new-worker-host').value.trim(),controller_url:document.querySelector('#controller-url').value.trim(),suite_root:document.querySelector('#suite-root').value.trim(),token:document.querySelector('#worker-token').value,password:document.querySelector('#worker-password').value};if(!body.worker_id||!body.ssh_host||!body.token){toast('请填写 Worker 名称、SSH 主机和 Worker Token');return}if(!body.password){toast('请重新填写 SSH 密码；出于安全考虑部署后不会保留密码');return}document.querySelector('#new-worker-id').value=body.worker_id;button.disabled=true;button.textContent='安装并等待注册…';try{await api('/api/cluster/workers/deploy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Worker 已安装并成功注册');document.querySelector('#worker-password').value='';document.querySelector('#onboarding').hidden=true;await refresh()}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent='自动部署'}}
window.showJob=showJob;window.cancelJob=cancelJob;window.deployArchive=deployArchive;document.querySelector('#refresh').onclick=refresh;document.querySelector('#reload-library').onclick=loadLibrary;document.querySelector('#show-onboarding').onclick=()=>{document.querySelector('#onboarding').hidden=false;updateDeployCommand()};document.querySelector('#close-onboarding').onclick=()=>document.querySelector('#onboarding').hidden=true;['new-worker-id','new-worker-host','controller-url','suite-root'].forEach(id=>document.querySelector(`#${id}`).oninput=updateDeployCommand);document.querySelector('#controller-url').value=location.origin;document.querySelector('#copy-deploy').onclick=()=>navigator.clipboard.writeText(document.querySelector('#deploy-command').textContent).then(()=>toast('命令已复制'));document.querySelector('#auto-deploy').onclick=autoDeployWorker;refresh();setInterval(refresh,15000);
