"""GMS Remote Test - API 路由注册"""

from . import (
    agent,
    apk,
    assets,
    audit,
    config,
    desktop,
    devices,
    firmware,
    gms_update_monitor,
    integrations,
    mainline_known_issues,
    notifications,
    reports,
    system,
    terminal,
    tests,
    users,
)

ALL_ROUTERS = [
    agent.router,
    apk.router,
    assets.router,
    audit.router,
    config.router,
    desktop.router,
    devices.router,
    firmware.router,
    gms_update_monitor.router,
    integrations.router,
    mainline_known_issues.router,
    notifications.router,
    reports.router,
    system.router,
    terminal.router,
    tests.router,
    users.router,
]
